services:
  - type: web
    name: zk-clipboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: CLIP_PORT
        value: 5002
